<a href="https://colab.research.google.com/github/jaehyeon26/tensorflow2/blob/main/colab/tensor_grammer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Tensorflow

In [2]:
import numpy as np
import tensorflow as tf

1D Tensor
2D Tensor
3D Tensor - (행개수, 열개수, 차원수)
가장 안쪽 대괄호 안의 값 개수 == 열개수
다음 괄호 안의 대괄의 개수 == 행개수
그 다음 괄호 안의 대괄호 개수 == 폭개수


In [19]:
#T3
t1 = tf.constant([1,2,3])
print(t1)
print(tf.rank(t1))
print(tf.rank(tf.rank(t1)))

#T2
t2 = tf.constant([[1,2],[1,2],[1,2]])
print(t2)

#T3
t3 = tf.constant([[[1,1,1],[2,2,2]]])
                 #[[3,3,3],[4,4,4]],
                 #[[5,5,5],[6,6,6]]
print(t3)

#T4


tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(
[[1 2]
 [1 2]
 [1 2]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[[1 1 1]
  [2 2 2]]], shape=(1, 2, 3), dtype=int32)
